@startuml

skinparam ComponentStyle rectangle
left to right direction
set namespaceSeparator none

node "Mulesoft dev" {
    
    package "http://ny-dev-nit-nis-api.awscfs.frb.pvt/dev" {
        [ctd\napi\nstreaming\nspline] as assetdev
    
    }
 
    package "http://ny-dev-nit-nis-api.awscfs.frb.pvt/test" {
        [ctd\napi\nstreaming\nspline] as assettest
    
        'assetdev -[hidden]-- assettest
    }

    package "http://ny-dev-nit-nis-api.awscfs.frb.pvt/uat" {
        [ctd\napi\nstreaming\nspline] as assetuat
    
        'assetdev -[hidden]-- assettest
    }
    'assetdev --> assettest
}
'left to right direction

node "DNS//alias dev" {
    [DNS://npqs-dev-api.frb.org] as aliasdev
}

node "DNS//alias test" {
    [DNS://npqs-test-api.frb.org] as aliastest
}
node "DNS//alias uat" {
    [DNS://npqs-uat-api.frb.org] as aliasuat
}


'OCP4 -dev

node "OCP4 db1me1" {
    
    package "dev-dev" {
        [http://ny-dev-cc1-npqs-01.apps.db1me1.dev.ocp.fras.frb.org] as ablaydevdev
    
    }
 
    package "dev-test" {
        [http://ny-dev-cc1-npqs-01.apps.db1me1.dev.ocp.fras.frb.org] as ablaydevtest
    
    }

    package "dev-uat" {
        [http://ny-dev-cc1-npqs-01.apps.db1me1.dev.ocp.fras.frb.org] as ablaydevuat
    
    
    }
    
}

assetdev --> aliasdev
assettest --> aliastest
assetuat --> aliasuat
aliasdev --> ablaydevdev
aliastest --> ablaydevtest
aliasuat --> ablaydevuat

json JSON {
   "fruit":"Apple",
   "size":"Large",
   "color": ["Red", "Green"]
}

@enduml