@startuml

skinparam ComponentStyle rectangle
left to right direction
set namespaceSeparator none

node "Rest API Clients - uat" {

    package "TradingApp/devuat" {
        [Market\nTheoretical] as restclientuat
    
    }

}

node "API Proxy - dev" {
    
    package "baseurl/dev" {
        [bb price\nmarketprice\ntheoreticalprice] as assetdev
    
    }
 
    package "baseurl/test" {
        [bb price\nmarketprice\ntheoreticalprice] as assettest
    
        'assetdev -[hidden]-- assettest
    }

    package "baseurl/uat" {
        [bb price\nmarketprice\ntheoreticalprice] as assetuat
    
        'assetdev -[hidden]-- assettest
    }
    'assetdev --> assettest
}
'left to right direction

node "DNS//alias - dev" {
    [DNS://dev-dns-url] as aliasdev
}

node "DNS//alias test" {
    [DNS://test-dns-url] as aliastest
}
node "DNS//alias uat" {
    [DNS://uat-dns-url] as aliasuat
}


'On-prem Private Cloud (OCP4) -dev

node "Onprem resource-servers" {
    
    package "dev-dev" {
        [http://dev-rscsrvr-baseurl] as ablaydevdev
    
    }
 
    package "dev-test" {
        [http://dev-rscsrvr-baseurl] as ablaydevtest
    
    }

    package "dev-uat" {
        [http://dev-rscsrvr-baseurl] as ablaydevuat
    
    
    }
    
}

node "Onprem pricing-server" {
    
    package "dev" {
        [dev-linuxsrvr] as pricingdev
    
    }
 
    package "dev2" {
        [dev-linuxsrvr] as pricingdev2
    
    }

    package "integration" {
        [dev-linuxsrvr] as pricingint
    
    
    }
    
}

assetdev --> aliasdev
assettest --> aliastest
assetuat --> aliasuat
aliasdev --> ablaydevdev
aliastest --> ablaydevtest
aliasuat --> ablaydevuat
restclientuat --> assetuat
ablaydevuat --> pricingint
'ablaydevtest --> onprempricingqa

@enduml