#!/bin/bash
echo -e "e-[setup_prjenv_api]\n"
#
# set env vars to make things easier
#
API_ROOT=APIs
API_ROOT_PROJECT=API-Intg
API_PROJECT_GROUP=STUDIO-LRN-MS
API_PROJECT_NAME=bad-price-api00-b1b4
#
# dirs
#
API_ROOT_DIR=/c/pjs/${API_ROOT}
API_ROOT_PROJECT_DIR=${API_ROOT_DIR}/${API_ROOT_PROJECT}
API_PROJECT_GROUP_DIR=${API_ROOT_PROJECT_DIR}/${API_PROJECT_GROUP}
API_PROJECT_NAME_DIR=${API_PROJECT_GROUP_DIR}/${API_PROJECT_NAME}
#
# export
#
export API_ROOT API_ROOT_DIR
export API_ROOT_PROJECT API_ROOT_PROJECT_DIR
export API_PROJECT_GROUP API_PROJECT_GROUP_DIR
export API_PROJECT_NAME API_PROJECT_NAME_DIR
#
# show
#

echo API_ROOT=$API_ROOT
echo API_ROOT_PROJECT=$API_ROOT_PROJECT
echo API_PROJECT_GROUP=$API_PROJECT_GROUP
echo API_PROJECT_NAME=$API_PROJECT_NAME
echo -e "\n"
echo API_ROOT_DIR=$API_ROOT_DIR
echo API_ROOT_PROJECT_DIR=$API_ROOT_PROJECT_DIR
echo API_PROJECT_GROUP_DIR=$API_PROJECT_GROUP_DIR
echo API_PROJECT_NAME_DIR=$API_PROJECT_NAME_DIR
#
# alias
alias cdr='cd ${API_ROOT_DIR}'
alias cdg='cd ${API_PROJECT_GROUP_DIR}'
alias cdp='cd ${API_PROJECT_NAME_DIR}'
#
echo -e "\nx-[setup_prjenv_api]"
